import React from "react"
import AniLink from "gatsby-plugin-transition-link/AniLink"

const Navlinks = () => (
  <>
    <AniLink
      cover
      direction="left"
      bg="#fff"
      duration={1}
      className="navbar-item"
      to="/page-2"
    >
      Sobre
    </AniLink>
    <AniLink
      className="navbar-item"
      cover
      to="/about"
      direction="left"
      duration={1}
      bg="#fff"
    >
      Equipe
    </AniLink>
    <AniLink
      className="navbar-item"
      cover
      to="/about"
      direction="left"
      duration={1}
      bg="#fff"
    >
      Projetos
    </AniLink>
    <AniLink
      className="navbar-item"
      cover
      to="/about"
      direction="left"
      duration={1}
      bg="#fff"
    >
      Publicações
    </AniLink>
    <AniLink
      className="navbar-item"
      cover
      to="/about"
      direction="left"
      duration={1}
      bg="#fff"
    >
      Parceiros
    </AniLink>
    <AniLink
      className="navbar-item"
      cover
      to="/about"
      direction="left"
      duration={1}
      bg="#fff"
    >
      Galeria
    </AniLink>
    <AniLink
      className="navbar-item"
      cover
      to="/contato"
      direction="left"
      duration={1}
      bg="#fff"
    >
      Contato
    </AniLink>
  </>
)
export default Navlinks
